### ISSUE TITLE
You Seem to Have Committed the Public Folder into the Root :)

### ISSUE THREAD

**Issue by recipher** [chrisscoular/5dayForecast#1]
Hi. I'm evaluating this on behalf of LBG. Your source code has disappeared. Rather than reject your code on that basis, I thought I'd let you fix it first.

Thanks :)

**Comment by chrisscoular** [comment]
Hi.

I am glad you pointed this out as I was unaware this had happened, Thank You.

The deploy of the build overwrote the source code. The cause was not setting up the branch gh-pages to use for the deployment. I have corrected this and the source code and app should now be visible.
